alias sv="source venv/bin/activate"
alias ssh-alan="ssh kylehsu@alan.ist.berkeley.edu"
alias cd-maml="cd /home/kylehsu/experiments/maml"
alias ssh-korova="ssh kylehsu@korova.banatao.berkeley.edu"
alias svdd="source /home/kylehsu/venvs/doodad/bin/activate"
alias umrl="source activate umrl && cd ~/experiments/umrl"
alias ssh-gce="ssh kylehsu@35.247.17.142"
